version: "3.9"

services:
  db:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_DB: init-keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - .docker/db:/var/lib/postgresql@16/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: init-keycloak
    environment:
      DATABASE_HOST: host.docker.internal
      REDIS_HOST: host.docker.internal
    ports:
      - "3200:3200"
    depends_on:
      - db
    volumes:
      - ./src:/app/src
